services:
  caddy:
    image: caddy:2.8
    volumes:
      - ./etc/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./data/static:/app/static
    ports:
      - 80:80
      - 443:443
    environment:
      - JANUS_VIDEO=video.tucanorobotics.co

  redis:
    image: redis:6-alpine
    expose:
      - 6379

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8000 ikaro.asgi:application
    expose:
      - 8000
    environment:
      - DEBUG=False
      - SERVER_ENV=PROD
      - REDIS_HOST=redis
      - ALLOWED_HOSTS=ikaro.tucanorobotics.co
      - JANUS_ENDPOINT=wss://ikaro.tucanorobotics.co/video
    volumes:
      - ./env:/env
      - ./data:/data

volumes:
  caddy_data:
  caddy_config:
