services:
  caddy:
    image: caddy:2.8
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 3000:3000

  redis:
    image: redis:6-alpine
    expose:
      - 6379

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    environment:
      SERVER_ENV: DEV
      REDIS_HOST: redis
    volumes:
      - ./ikarodjango:/opt/ikaro/ikarodjango
      - ./env:/opt/ikaro/env
    tty: true

  webpack:
    build:
      context: . 
      dockerfile: ./Dockerfile.webpack
    image: ikaro:webpack
    command: webpack --mode development --watch
    environment:
      - JANUS_ENDPOINT=ws://janus:8188
    volumes:
      - ./ikarodjango/js:/opt/ikaro/ikarodjango/js
      - ./ikarodjango/static:/opt/ikaro/ikarodjango/static
      # Hide local node_modules
      - ./ikarodjango/js/node_modules:/src/node_modules

  janus:
    image: canyan/janus-gateway:latest
    ports:
      - 8188:8188
      - 8088:8088
      - 8089:8089
      - 8889:8889
      - 8000:8000
      - 7088:7088
      - 7089:7089

volumes:
  caddy_data:
  caddy_config:
