version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000
    links:
      - "django"
    volumes:
      - ./etc/nginx/ikaro.docker.conf:/etc/nginx/nginx.conf
      - ./ikarodjango:/opt/ikaro/ikarodjango
      - ./ikarodjango/static:/opt/ikaro/ikarodjango/static

  redis:
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data

  django:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 ikaro.asgi:application
    expose:
      - 8000
    environment:
      SERVER_ENV: DEV
      REDIS_HOST: redis
    volumes:
      - ./ikarodjango:/opt/ikaro/ikarodjango
      - ./env:/opt/ikaro/env
    depends_on:
      redis:
        condition: service_started

  webpack:
    build:
      context: . 
      dockerfile: ./Dockerfile.webpack
    image: ikaro:webpack
    command: sh -c "(webpack --mode development --watch --info-verbosity verbose &)| cat"
    stdin_open: true
    tty: true
    volumes:
      - ./ikarodjango/js:/opt/ikaro/ikarodjango/js
      - ./ikarodjango/static:/opt/ikaro/ikarodjango/static
      # Hide local node_modules
      - ./ikarodjango/js/node_modules:/src/node_modules
