version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d
      - ./data:/opt/ikaro/data
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  web:
    build: .
    command: python ikarodjango/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/ikaro

  certbot:
    image: certbot/certbot
    volumes:
      - .:/opt/ikaro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/opt/ikaro --email jose@tucanoar.com --agree-tos --no-eff-email --staging -d tucanoar.com  -d www.tucanoar.com 
