version: '3'

services:
  redis:
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data

  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./ikarodjango:/opt/ikaro/ikarodjango

