version: '3'

services:
  redis:
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      SERVER_ENV: DEV
      REDIS_HOST: redis
    volumes:
      - ./ikarodjango:/opt/ikaro/ikarodjango
      - ./env:/opt/ikaro/env

  webpack:
    build:
      context: . 
      dockerfile: ./Dockerfile.webpack
    image: ikaro:webpack
    command: webpack --mode development --watch
    stdin_open: true
    tty: true
    volumes:
      - ./ikarodjango/js:/opt/ikaro/ikarodjango/js
      - ./ikarodjango/static:/opt/ikaro/ikarodjango/static
      # Hide local node_modules
      - ./ikarodjango/js/node_modules:/src/node_modules

  janus:
    image: canyan/janus-gateway:master
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      # - "80:80"
      - "7088:7088" # admin
      - "8088:8088" # drone
      - "8188:8188" # front
      # - "7089:7089"
      # - "8089:8089"
      # - "8889:8889"
    volumes:
      - ./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg
      - ./etc/janus/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg
      - ./etc/janus/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg
