# Generated by Django 3.0.2 on 2020-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikaro', '0002_auto_20200517_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debug_toolbar',
            field=models.BooleanField(default=False),
        ),
    ]
