# Generated by Django 3.1.4 on 2021-04-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikaro', '0004_auto_20201229_1500'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
