# Generated by Django 3.1.4 on 2020-12-29 15:02

from django.db import migrations, models
import ikaro.utils


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mavlinkmessage',
            name='params',
            field=models.JSONField(default=dict, encoder=ikaro.utils.ExtendedEncoder),
        ),
    ]
