# Generated by Django 3.1.4 on 2021-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20201229_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='alias',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
