# Generated by Django 3.1.4 on 2021-04-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20201229_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_viewers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
